# ZeroClaw Configuration
# Deploys ZeroClaw configuration files generated by SecGen

class zeroclaw::config(
  Array[String] $hackerbot_configs = [],
) {
  # Deploy ZeroClaw configurations generated by SecGen
  # Each config is a JSON object with 'zeroclaw_toml_config' key
  
  $hackerbot_configs.each |$counter, $config_pair| {
    $parsed_pair = parsejson($config_pair)
    
    # Deploy ZeroClaw TOML configuration
    file { "/opt/zeroclaw/hackerbot/bot_${counter}.toml":
      ensure  => file,
      content => $parsed_pair['zeroclaw_toml_config'],
      mode    => '0600',
      owner   => 'root',
      group   => 'root',
      notify  => Service['zeroclaw'],
    }
  }

  # Create main config.toml that includes all bot configs
  file { '/opt/zeroclaw/config.toml':
    ensure  => file,
    content => template('zeroclaw/config.toml.erb'),
    mode    => '0600',
    owner   => 'root',
    group   => 'root',
    notify  => Service['zeroclaw'],
  }

  # Create SecGen datastore symlink if it exists
  file { '/opt/zeroclaw/datastore.json':
    ensure => link,
    target => '/var/lib/secgen/datastore.json',
    require => File['/opt/zeroclaw'],
  }
}
