#!/usr/bin/ruby
# ZeroClaw Config Builder for SecGen Integration
# Generates ZeroClaw TOML configuration from SecGen datastore values
# 
# This module creates TOML configs that ZeroClaw can use for cybersecurity training scenarios
# It runs alongside the existing HackerbotConfigGenerator to support parallel deployment

require 'json'
require 'securerandom'
require 'erb'
require 'time'

class ZeroClawConfigBuilder
  attr_accessor :accounts
  attr_accessor :flags
  attr_accessor :root_password
  attr_accessor :irc_server_ip
  attr_accessor :irc_port
  attr_accessor :scenario_id
  attr_accessor :templates_path
  
  def initialize
    self.accounts = []
    self.flags = []
    self.root_password = ''
    self.irc_server_ip = 'localhost'
    self.irc_port = 6668
    self.scenario_id = ''
    self.templates_path = File.expand_path('../../modules/generators/structured_content/hackerbot_config', __dir__)
  end
  
  # Generate ZeroClaw TOML config from SecGen datastore values
  def generate_toml_config(scenario_type = 'hacker_vs_hackerbot_1')
    accounts_json = accounts.map { |a| JSON.parse(a) }
    first_account = accounts_json[0] || {}
    second_account = accounts_json[1] || {}
    
    main_user = first_account['username'] || 'student'
    main_password = first_account['password'] || 'password123'
    
    # Ensure we have enough flags
    required_flags = 10
    while flags.length < required_flags
      flags << "SEC GEN{#{SecureRandom.hex(8)}}"
    end
    
    template_file = find_template_for_scenario(scenario_type)
    
    if template_file && File.exist?(template_file)
      template = ERB.new(File.read(template_file), 0, '<>-')
      return template.result(get_binding)
    else
      # Fallback to generic template
      generate_generic_toml(first_account, second_account, main_user, main_password)
    end
  end
  
  def find_template_for_scenario(scenario_type)
    template_paths = [
      "#{templates_path}/#{scenario_type}/templates/zeroclaw_config.toml.erb",
      "#{templates_path}/generic/templates/zeroclaw_config.toml.erb",
      "/opt/zeroclaw/templates/config.toml.erb"
    ]
    
    template_paths.find { |path| File.exist?(path) }
  end
  
  def generate_generic_toml(first_account, second_account, main_user, main_password)
    <<~TOML
      # ZeroClaw Hackerbot Configuration
      # Generated by SecGen ZeroClawConfigBuilder
      # Scenario: #{scenario_id}
      # Generated: #{Time.now.iso8601}
      
      [hackerbot]
      scenario_id = "#{scenario_id}"
      irc_server = "#{irc_server_ip}"
      irc_port = #{irc_port}
      default_personality = "red_team"
      
      [secgen]
      enabled = true
      datastore_path = "/var/lib/secgen/datastore.json"
      main_username = "#{main_user}"
      main_password = "#{main_password}"
      
      [[flags]]
      id = "flag_1"
      value = "#{flags[0] || 'SEC GEN{placeholder}'}"
      description = "First flag"
      
      [[flags]]
      id = "flag_2"
      value = "#{flags[1] || 'SEC GEN{placeholder}'}"
      description = "Second flag"
      
      [[scenarios]]
      index = 0
      title = "Initial Access"
      prompt = "Connect to the target system and gain initial access..."
      flag_id = "flag_1"
      
      [[scenarios]]
      index = 1
      title = "Privilege Escalation"
      prompt = "Escalate your privileges to root..."
      flag_id = "flag_2"
      
      [agents.red_team]
      provider = "ollama"
      model = "gemma3:1b"
      agentic = true
      allowed_tools = ["shell", "scenario_manager", "secgen_datastore_query"]
      
      [agents.blue_team]
      provider = "ollama"
      model = "gemma3:1b"
      agentic = true
      allowed_tools = ["shell", "scenario_manager", "secgen_datastore_query"]
    TOML
  end
  
  def get_binding
    binding
  end
end
